version: '3'
services:
  master:
    build: ./jenkins-master
    image: jenkins-master:0.1
    ports:
      - "50000:50000"
    volumes:
      - "~/.ssh/:/var/jenkins_home/.ssh/"     
      - jenkins-log:/var/log/jenkins
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins-net
  nginx:
    build: ./jenkins-nginx
    image: jenkins-nginx:0.1
    ports:
      - "80:80"
    networks:
      - jenkins-net
  slave:
    build: ./jenkins-slave
    image: jenkins-slave:0.1
  proxy:
    build: ./docker-proxy
    image: docker-proxy:0.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      jenkins-net:
        aliases:
          - proxy1
volumes:
  jenkins-data:
  jenkins-log:
networks:
  jenkins-net:
